name: learn-github-actions
run-name: ${{github.actor}} dang thu tim hieu Github Actions
on:
  push:
jobs:
  check-bats-version:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Bats
        run: npm install -g bats
      - name: Check Bats version
        run: bats -v
